export const expectedFileMetadata = [
	{
		filename: 'img-1.jpg',
		metadata: {
			streams: [
				{
					index: 0,
					codec_name: 'mjpeg',
					codec_long_name: 'Motion JPEG',
					profile: 'Progressive',
					codec_type: 'video',
					codec_tag_string: '[0][0][0][0]',
					codec_tag: '0x0000',
					width: 1280,
					height: 1280,
					coded_width: 1280,
					coded_height: 1280,
					closed_captions: 0,
					film_grain: 0,
					has_b_frames: 0,
					sample_aspect_ratio: '1:1',
					display_aspect_ratio: '1:1',
					pix_fmt: 'yuvj420p',
					level: '-99',
					color_range: 'pc',
					color_space: 'bt470bg',
					color_transfer: 'unknown',
					color_primaries: 'unknown',
					chroma_location: 'center',
					field_order: 'unknown',
					refs: 1,
					id: 'N/A',
					r_frame_rate: '25/1',
					avg_frame_rate: '25/1',
					time_base: '1/25',
					start_pts: 0,
					start_time: 0,
					duration_ts: 1,
					duration: 0.04,
					bit_rate: 'N/A',
					max_bit_rate: 'N/A',
					bits_per_raw_sample: 8,
					nb_frames: 'N/A',
					nb_read_frames: 'N/A',
					nb_read_packets: 'N/A',
					disposition: {
						default: 0,
						dub: 0,
						original: 0,
						comment: 0,
						lyrics: 0,
						karaoke: 0,
						forced: 0,
						hearing_impaired: 0,
						visual_impaired: 0,
						clean_effects: 0,
						attached_pic: 0,
						timed_thumbnails: 0,
						non_diegetic: 0,
						captions: 0,
						descriptions: 0,
						metadata: 0,
						dependent: 0,
						still_image: 0,
						multilayer: 0,
					},
				},
			],
			format: {
				nb_streams: 1,
				nb_programs: 0,
				nb_stream_groups: 0,
				format_name: 'image2',
				format_long_name: 'image2 sequence',
				start_time: 0,
				duration: 0.04,
				size: 428621,
				bit_rate: 85724200,
				probe_score: 50,
			},
			chapters: [],
		},
	},
	{
		filename: 'img-2.png',
		metadata: {
			streams: [
				{
					index: 0,
					codec_name: 'mjpeg',
					codec_long_name: 'Motion JPEG',
					profile: 'Baseline',
					codec_type: 'video',
					codec_tag_string: '[0][0][0][0]',
					codec_tag: '0x0000',
					width: 1280,
					height: 1024,
					coded_width: 1280,
					coded_height: 1024,
					closed_captions: 0,
					film_grain: 0,
					has_b_frames: 0,
					sample_aspect_ratio: '1:1',
					display_aspect_ratio: '5:4',
					pix_fmt: 'yuvj420p',
					level: '-99',
					color_range: 'pc',
					color_space: 'bt470bg',
					color_transfer: 'unknown',
					color_primaries: 'unknown',
					chroma_location: 'center',
					field_order: 'unknown',
					refs: 1,
					id: 'N/A',
					r_frame_rate: '25/1',
					avg_frame_rate: '25/1',
					time_base: '1/25',
					start_pts: 0,
					start_time: 0,
					duration_ts: 1,
					duration: 0.04,
					bit_rate: 'N/A',
					max_bit_rate: 'N/A',
					bits_per_raw_sample: 8,
					nb_frames: 'N/A',
					nb_read_frames: 'N/A',
					nb_read_packets: 'N/A',
					disposition: {
						default: 0,
						dub: 0,
						original: 0,
						comment: 0,
						lyrics: 0,
						karaoke: 0,
						forced: 0,
						hearing_impaired: 0,
						visual_impaired: 0,
						clean_effects: 0,
						attached_pic: 0,
						timed_thumbnails: 0,
						non_diegetic: 0,
						captions: 0,
						descriptions: 0,
						metadata: 0,
						dependent: 0,
						still_image: 0,
						multilayer: 0,
					},
				},
			],
			format: {
				nb_streams: 1,
				nb_programs: 0,
				nb_stream_groups: 0,
				format_name: 'image2',
				format_long_name: 'image2 sequence',
				start_time: 0,
				duration: 0.04,
				size: 157662,
				bit_rate: 31532400,
				probe_score: 50,
			},
			chapters: [],
		},
	},
	{
		filename: 'img-3.gif',
		metadata: {
			streams: [
				{
					index: 0,
					codec_name: 'gif',
					codec_long_name: 'CompuServe GIF (Graphics Interchange Format)',
					profile: 'unknown',
					codec_type: 'video',
					codec_tag_string: '[0][0][0][0]',
					codec_tag: '0x0000',
					width: 256,
					height: 175,
					coded_width: 256,
					coded_height: 175,
					closed_captions: 0,
					film_grain: 0,
					has_b_frames: 0,
					sample_aspect_ratio: 'N/A',
					display_aspect_ratio: 'N/A',
					pix_fmt: 'bgra',
					level: '-99',
					color_range: 'unknown',
					color_space: 'unknown',
					color_transfer: 'unknown',
					color_primaries: 'unknown',
					chroma_location: 'unspecified',
					field_order: 'unknown',
					refs: 1,
					id: 'N/A',
					r_frame_rate: '100/3',
					avg_frame_rate: '100/3',
					time_base: '1/100',
					start_pts: 0,
					start_time: 0,
					duration_ts: 216,
					duration: 2.16,
					bit_rate: 'N/A',
					max_bit_rate: 'N/A',
					bits_per_raw_sample: 'N/A',
					nb_frames: 72,
					nb_read_frames: 'N/A',
					nb_read_packets: 'N/A',
					disposition: {
						default: 0,
						dub: 0,
						original: 0,
						comment: 0,
						lyrics: 0,
						karaoke: 0,
						forced: 0,
						hearing_impaired: 0,
						visual_impaired: 0,
						clean_effects: 0,
						attached_pic: 0,
						timed_thumbnails: 0,
						non_diegetic: 0,
						captions: 0,
						descriptions: 0,
						metadata: 0,
						dependent: 0,
						still_image: 0,
						multilayer: 0,
					},
				},
			],
			format: {
				nb_streams: 1,
				nb_programs: 0,
				nb_stream_groups: 0,
				format_name: 'gif',
				format_long_name: 'CompuServe Graphics Interchange Format (GIF)',
				start_time: 0,
				duration: 2.16,
				size: 743399,
				bit_rate: 2753329,
				probe_score: 100,
			},
			chapters: [],
		},
	},
]
